added mailto to button in section "O nas"
infoshareacademy/jfdz6-npnd pull request #6
Opened 2017-09-13 06:20 UTC by Demytruk

mailto

2017-09-14 05:41 UTC, piotrbaranski reviewed
Nie wiem czy to przez fakt, iż nie mam skonfigurowanego konta outlook/thunderbird, ale po pokazaniu się okienka, nie ma adresata (np. natalia@analizatorfinansowy.pl). Czy tylko ja tak mam?
Podobnie jak odnośniki do social media miały odsyłać do konkretnych stron, mam wrażenie, że na prezentacji może zostać poruszony temat, że adresy email są nieprawdziwe. Może damy realne? Może kiedyś jakiś pracodawca zobaczy tą stronę, będzie chciał się z nami skontaktować i kliknie w te przyciski? :)

2017-09-17 06:16 UTC, piotrbaranski requested changes
I przy adresie Nokodema jest literówka  - "Nikoem" zamiast "Nikodem" ;)

2017-09-17 06:44 UTC, Demytruk commented
Literówka poprawiona :)

2017-09-17 08:07 UTC, klnwsk approved these changes

2017-09-17 08:07 UTC, piotrbaranski approved these changes
+1

2017-09-17 08:09 UTC, merged